name: wfmge
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7
  stream_transform: ^2.1.1
  dio: ^5.8.0+1
  envied: ^1.1.1
  animations: ^2.0.11
  flutter_svg: ^2.2.0
  collection: ^1.19.1
  intl: ^0.20.2
  get_it: ^8.0.3
  logger: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  generate: true
